name = "munin"
description = "A lightweight developer companion for embedded Ravenscar applications."
version = "0.1.0-dev"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = "https://github.com/reznikmm/munin"
tags = ["embedded", "analyzer", "realtime"]

executables = ["munin"]

[build-switches]
"*".Ada_Version = "Ada2022"
development.optimization = ["-O0"]
development.style_checks = ["-gnaty", "-gnaty-B"]
development.contracts = "Yes"
"*".debug_info = "Yes"

[[depends-on]]
libadalang = "^26.0.0"
vss_extra = "^26.0.0"

[[actions]]
type = "test"
command = ["testsuite/run.sh"]

[[actions]]
type = "pre-build"
# The hack works only with:
# alr settings --global --set dependencies.shared false
command = ["find", ".", "-name", "langkit_support-prettier_utils.adb", "-exec", "sed", "-i", "-e", "35s/: in/: aliased in/", "-e", "538s/: in/: aliased in/", "{}", ";"]

[[pins]]
libgpr2 = { url="https://github.com/AdaCore/gpr/", commit="12c649aa4d4c4e334b8271ac619500532aaeb21f" }
libgpr  = { url="https://github.com/reznikmm/gprbuild/", commit="841bfb074a4aa9729e067eb54f34100b55c05dd0" }
