version = 1
SPDX-PackageName = "munin"
SPDX-PackageSupplier = "Max Reznik <reznikmm@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/reznikmm/munin"

[[annotations]]
path = ["README.md", "alire.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Max Reznik <reznikmm@gmail.com>"
SPDX-License-Identifier = "Apache-2.0 WITH LLVM-exception"
